server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 120000 # 2 minutes
            response-timeout: 120s
          default-filters:
            - name: Retry
              args:
                retries: 4
                methods: GET, POST
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 2s
                  maxBackoff: 30s
                  factor: 2
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**, /api/users/**
            - id: chat-service
              uri: ${CHAT_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/messages/**, /ws/**
